package sample.config;

import org.apache.commons.dbcp.BasicDataSource;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.simple.SimpleJdbcTemplate;

@Configuration
public class AppConfig {
    @Bean
    public SimpleJdbcTemplate simpleJdbcTemplate() throws DataAccessException {
        BasicDataSource dataSource = new BasicDataSource();
        dataSource.setUrl("jdbc:mysql://localhost:3306/twimini_db");
        dataSource.setDriverClassName("com.mysql.jdbc.Driver");
        dataSource.setUsername("root");
        dataSource.setPassword("root");
//        dataSource.setUrl("jdbc:hsqldb:mem:todo");
//        dataSource.setDriverClassName("org.hsqldb.jdbcDriver");
        SimpleJdbcTemplate db = new SimpleJdbcTemplate(dataSource);
//        db.update("CREATE TABLE todos (" +
//            "id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY," +
//            "user_id INTEGER NOT NULL," +
//            "description varchar(128) DEFAULT '' NOT NULL" +
//            ")");
//        db.update("CREATE TABLE users (" +
//            "id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY," +
//            "username varchar(128) NOT NULL," +
//            "password varchar(128) NOT NULL" +
//            ")");
        return db;
    }
}